#!/usr/bin/env python
"""Emit the polyphase sinc coefficient table as GDB register writes for a JTAG load.

ONE SOURCE OF TRUTH. The table comes from gen_resample_vectors.sinc_table_q15(), the same function
the RTL bench checks the hardware against, so host and bench cannot drift.

WHY THE HOST AND NOT FIRMWARE. 256 phases x 32 taps x int16 = 16 KB, and it does not fit: the app's
.rodata lives in the 256 KB L2 scratchpad, which is already full -- linking it overflowed the region
by 15,584 bytes, so even a quarter-size table would not fit either. Recomputing it in C is not an
option: it needs sin(), and this firmware links without libm. It does not need to be in the image
anyway -- the table is SCENE-INDEPENDENT, a function of fractional delay only, so it is a one-time
push that survives until the fabric is reset.

Usage:  python mpfs/host/gen_sinc_table_gdb.py       -> mpfs/host/jtag_full/sinc_table.gdb
        then load it with mpfs/host/run_sinc_table_load.sh
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / ".." / "fpga" / "tb"))
import gen_resample_vectors as G                                    # noqa: E402

OUT = (HERE / "jtag_full" / "sinc_table.gdb").resolve()
K_RESAMPLE = 0x60003000
RSV_TAB_CTRL = 0x2C
RSV_TAB_DATA = 0x30


def main():
    taps, phases = G.SINC_TAPS, G.SINC_PHASES
    tab = G.sinc_table_q15(phases, taps)

    # invariants the RTL depends on -- assert here so a bad table can never reach the board
    for ph, row in enumerate(tab):
        assert sum(row) == (1 << 15), f"phase {ph} DC gain {sum(row)} != 32768"
        assert all(-32768 <= v <= 32767 for v in row), f"phase {ph} has a tap outside int16"

    lines = [
        "# GENERATED by mpfs/host/gen_sinc_table_gdb.py -- DO NOT EDIT.",
        "# Polyphase truncated-sinc coefficients, Q15, phase-major/tap-minor: exactly the order",
        "# TAB_DATA expects. Every phase sums to 2^15 and every tap fits int16, both asserted at",
        "# generation -- unity is 32768, one past the int16 rail, so the rounding residual is spread",
        "# across taps rather than dumped on the largest one (doing that naively wrapped a tap",
        "# negative and inverted the dominant coefficient, 2026-07-29).",
        "#",
        "# TAB_CTRL select is SPLIT: bit 2 is REWIND and predates the 5th table, so target 4 is",
        "# {bit3=1, bits[1:0]=0} = 0x8, plus 0x4 to rewind the shared pointer.",
        f"set *(unsigned int*)0x{K_RESAMPLE + RSV_TAB_CTRL:08x} = 0xc",
    ]
    for ph in range(phases):
        for tp in range(taps):
            v = tab[ph][tp] & 0xFFFF
            lines.append(f"set *(unsigned int*)0x{K_RESAMPLE + RSV_TAB_DATA:08x} = 0x{v:04x}")
    # The doubled backslash is deliberate: this must emit a LITERAL backslash-n into the gdb
    # script. A single one is a Python escape and splits the printf across two lines, which
    # gdb then rejects.
    lines += ["", "# readback: TAB_DATA returns tab_wptr, which must have wrapped to 0",
              f'printf ">>> tab_wptr after load = %u (expect 0)\\n", '
              f'*(unsigned int*)0x{K_RESAMPLE + RSV_TAB_DATA:08x}', ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"  wrote {OUT}")
    print(f"  {phases} phases x {taps} taps = {phases*taps} writes, all unity-gain, all int16")
    return 0


if __name__ == "__main__":
    sys.exit(main())
