#!/usr/bin/env bash
# Milestone-2 eMMC PROVISION iso-run: bulk single-block write of a DDR span to the
# eMMC INPUT partition (LBA 0x80000), read-back + CRC verify, WRITE LOOP TIMED.
# Mailbox trigger (cmd 'EPRV' 0x45505256); same FP6/JTAG hygiene as run_emmc_iso.sh
# (efp6, telnet 4444, graceful telnet shutdown, NEVER taskkill). Attach-in-place.
#
# Usage:  run_emmc_prov_iso.sh [SPAN_BYTES] [SLEEP_MS] [SRC_ADDR]
#   SPAN_BYTES : bytes to provision (block-multiple). Default 0x100000 (1 MiB).
#   SLEEP_MS   : how long to let the write+readback run before halting. Default 30000.
#   SRC_ADDR   : DDR source (default 0x88000000 = SIG region; uses resident DDR
#                content -- the firmware CRCs the source right before writing, so
#                source-vs-readback is self-consistent WITHOUT a JTAG data load).
# Prereq: board powered; eMMC-mux bitstream programmed; -DSAR_EMMC_ENABLE firmware
# flashed (run_program.sh). Prov result record @0xB005D000.
set -u
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/sar_env.sh"   # SAR_ROOT / tool paths (see config.yaml)
SPAN="${1:-0x100000}"
SLEEP_MS="${2:-30000}"
SRC="${3:-0x88000000}"
HERE="$(cd "$(dirname "$0")" && pwd)"
GDBSCRIPT="$HERE/jtag_full/emmc_prov_iso.gen.gdb"
GDBLOG="$HERE/jtag_full/emmc_prov_iso.log"
OOLOG="${GDBLOG%.log}.openocd.log"
NEW="$SAR_OPENOCD"
SC="$SAR_SOFTCONSOLE"
GDB="$SC/riscv-unknown-elf-gcc/bin/riscv64-unknown-elf-gdb.exe"
ELF="$HERE/../fpga/libero_sar/softconsole/mpfs-hal-ddr-demo/Icicle-Kit-DDR-666MHz-eNVM-Scratchpad-Release/mpfs-hal-ddr-demo.elf"
PY="$SAR_PYTHON"

# --- generate the gdb script with the span/sleep/src baked in --------------
cat > "$GDBSCRIPT" <<GDBEOF
# GENERATED by run_emmc_prov_iso.sh -- span=$SPAN sleep_ms=$SLEEP_MS src=$SRC
set pagination off
set confirm off
set architecture riscv:rv64
set mem inaccessible-by-default off
shell $PY $HERE/jtag_full/wait_port.py
target extended-remote localhost:3333
monitor mpfs.hart1_u54_1 arp_halt
thread 2
printf ">>> hart1 boot pc = 0x%016lx (expect u54_1 mailbox loop)\n", \$pc
# arm EPRV: base=src, len=span, cmd LAST (mailbox @0xB0058000)
set {unsigned int}0xB0058004 = $SRC
set {unsigned int}0xB0058008 = $SPAN
set {unsigned int}0xB005800C = 0
set {unsigned int}0xB0058010 = 0
set {unsigned int}0xB0058000 = 0x45505256
echo >>> EPRV armed (src=$SRC span=$SPAN). Resuming; provisioner writes then reads back...\n
monitor resume
monitor sleep $SLEEP_MS
monitor mpfs.hart1_u54_1 arp_halt
thread 2
printf ">>> post-run hart1 pc = 0x%016lx\n", \$pc
set \$magic  = *(unsigned int*)0xB005D000
set \$verd   = *(unsigned int*)0xB005D040
set \$wl     = *(unsigned int*)0xB005D018
set \$wus    = *(unsigned long*)0xB005D028
set \$rus    = *(unsigned long*)0xB005D030
set \$wcy    = *(unsigned long*)0xB005D038
printf ">>> prov magic=0x%08x verdict=%u (0=PASS)\n", \$magic, \$verd
printf ">>> init=%u write_st=%u read_st=%u fail_blk=0x%08x\n", \
  *(unsigned int*)0xB005D004, *(unsigned int*)0xB005D008, *(unsigned int*)0xB005D00C, *(unsigned int*)0xB005D024
printf ">>> byte_len=%u nblocks=%u dest_lba=0x%08x\n", \$wl, *(unsigned int*)0xB005D01C, *(unsigned int*)0xB005D020
printf ">>> crcE=0x%08x crcR=0x%08x  (must match for PASS)\n", *(unsigned int*)0xB005D010, *(unsigned int*)0xB005D014
printf ">>> write_us=%lu read_us=%lu write_cycles=%lu\n", \$wus, \$rus, \$wcy
if \$wus > 0
  printf ">>> WRITE %.3f MB/s (%.3f MiB/s)\n", (double)\$wl/(double)\$wus, (double)\$wl/(double)\$wus*0.953674316
end
if \$rus > 0
  printf ">>> READ  %.3f MB/s (%.3f MiB/s)\n", (double)\$wl/(double)\$rus, (double)\$wl/(double)\$rus*0.953674316
end
echo >>> clean teardown: resume + openocd shutdown\n
monitor resume
monitor shutdown
quit
GDBEOF

if tasklist 2>/dev/null | grep -qi openocd.exe; then
  echo ">>> ABORT: openocd.exe already running (stale) -- NOT force-killing (would wedge FP6)." ; exit 2
fi
: > "$OOLOG"; : > "$GDBLOG"
"$NEW/bin/openocd.exe" -s "$NEW/openocd/scripts" \
  --command "set DEVICE MPFS" \
  -c "telnet_port 4444" \
  -f board/microchip_riscv_efp6.cfg -l "$OOLOG" >/dev/null 2>&1 &
OO_PID=$!
sleep 14
"$GDB" -batch "$ELF" -x "$GDBSCRIPT" </dev/null > "$GDBLOG" 2>&1
echo "GDB_RC=$?" >> "$GDBLOG"
# graceful escape if gdb died before 'monitor shutdown' -- telnet shutdown, never taskkill
"$PY" - <<'PYEOF' 2>/dev/null || true
import socket,time
try:
    s=socket.create_connection(('127.0.0.1',4444),timeout=3); time.sleep(0.3)
    try: s.recv(4096)
    except Exception: pass
    s.sendall(b'shutdown\n'); time.sleep(0.5); s.close(); print("telnet-shutdown-sent")
except Exception as e: print("telnet-shutdown-skip:",e)
PYEOF
wait "$OO_PID" 2>/dev/null
echo ">>> eMMC provision iso-run done (span=$SPAN). Verdict + rate in: $GDBLOG"
grep -aE "verdict=|WRITE |READ |crcE=|byte_len=|boot pc|EPRV" "$GDBLOG" | tail -12
