#!/usr/bin/env bash
# Milestone-2d-2a: one-time JTAG restore of the packed eMMC INPUT image into DDR,
# so the provisioner (run_emmc_prov_iso.sh) can write it to the eMMC. This is the
# SLOW leg (~3 h over FP6 for ~97 MB) that eMMC provisioning exists to retire; it
# runs ONCE. After the restore, an on-hart CRC32 (mailbox 'CRC3') verifies the DDR
# image against the host CRC in SECONDS -- catching a corrupt load before the
# ~13 min provision. DDR persists across JTAG sessions (do NOT power-cycle after).
#
# Usage: run_emmc_restore.sh [IMG] [DST_ADDR] [EXPECT_CRC_HEX]
#   IMG            : packed image (default emmc_input.img)
#   DST_ADDR       : DDR load address (default 0x88000000 = SIG region)
#   EXPECT_CRC_HEX : host zlib.crc32 of IMG (default 0x58d0ea66) for the on-hart check
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
IMG="${1:-$HERE/emmc_input.img}"
DST="${2:-0x88000000}"
EXPECT="${3:-0x58d0ea66}"
IMG_UNIX="$(echo "$IMG" | sed 's#\\#/#g')"
# gdb.exe is native Windows: paths INSIDE the .gdb script (e.g. `restore`) are NOT
# MSYS-translated, so give it a Windows path (C:/...), not /c/... .
IMG_WIN="$(cygpath -m "$IMG_UNIX" 2>/dev/null || echo "$IMG_UNIX" | sed 's#^/\([a-zA-Z]\)/#\1:/#')"
BYTES="$(stat -c%s "$IMG_UNIX")"
GDBSCRIPT="$HERE/jtag_full/emmc_restore.gen.gdb"
GDBLOG="$HERE/jtag_full/emmc_restore.log"
OOLOG="${GDBLOG%.log}.openocd.log"
NEW="/c/Users/lkwangsi/Tools/openocd-new/xpack-openocd-0.12.0-4"
SC="/c/Microchip/SoftConsole-v2022.2-RISC-V-747"
GDB="$SC/riscv-unknown-elf-gcc/bin/riscv64-unknown-elf-gdb.exe"
ELF="$HERE/../fpga/libero_sar/softconsole/mpfs-hal-ddr-demo/Icicle-Kit-DDR-666MHz-eNVM-Scratchpad-Release/mpfs-hal-ddr-demo.elf"
PY="C:/ProgramData/Anaconda3-2025.12-1/python.exe"

cat > "$GDBSCRIPT" <<GDBEOF
# GENERATED by run_emmc_restore.sh -- img=$IMG_UNIX dst=$DST bytes=$BYTES expect=$EXPECT
set pagination off
set confirm off
set architecture riscv:rv64
set mem inaccessible-by-default off
shell $PY $HERE/jtag_full/wait_port.py
target extended-remote localhost:3333
monitor mpfs.hart1_u54_1 arp_halt
thread 2
printf ">>> hart1 boot pc = 0x%016lx (expect u54_1 mailbox loop)\n", \$pc
echo >>> restoring image into DDR (this is the ~3 h leg)...\n
restore $IMG_WIN binary $DST
echo >>> restore complete; on-hart CRC32 verify (mailbox 'CRC3')...\n
set {unsigned int}0xB0058004 = $DST
set {unsigned int}0xB0058008 = $BYTES
set {unsigned int}0xB005800C = 0
set {unsigned int}0xB0058010 = 0
set {unsigned int}0xB0058000 = 0x43524333
monitor resume
monitor sleep 8000
monitor mpfs.hart1_u54_1 arp_halt
thread 2
set \$crc = *(unsigned int*)0xB005800C
printf ">>> DDR image CRC32 = 0x%08x  (host expects %s)\n", \$crc, "$EXPECT"
if \$crc == $EXPECT
  echo >>> RESTORE VERIFIED: DDR image matches host. Ready to provision (run_emmc_prov_iso.sh).\n
else
  echo >>> RESTORE MISMATCH: DDR image CRC != host -- DO NOT provision; re-restore.\n
end
echo >>> leaving hart in mailbox loop; openocd shutdown (DDR persists -- no power-cycle)\n
monitor resume
monitor shutdown
quit
GDBEOF

if tasklist 2>/dev/null | grep -qi openocd.exe; then
  echo ">>> ABORT: openocd.exe already running (stale) -- NOT force-killing (would wedge FP6)." ; exit 2
fi
echo ">>> restoring $IMG_UNIX ($BYTES bytes) -> DDR $DST  [expect ~3 h]"
: > "$OOLOG"; : > "$GDBLOG"
"$NEW/bin/openocd.exe" -s "$NEW/openocd/scripts" \
  --command "set DEVICE MPFS" \
  -c "telnet_port 4444" \
  -f board/microchip_riscv_efp6.cfg -l "$OOLOG" >/dev/null 2>&1 &
OO_PID=$!
sleep 14
"$GDB" -batch "$ELF" -x "$GDBSCRIPT" </dev/null > "$GDBLOG" 2>&1
echo "GDB_RC=$?" >> "$GDBLOG"
"$PY" - <<'PYEOF' 2>/dev/null || true
import socket,time
try:
    s=socket.create_connection(('127.0.0.1',4444),timeout=3); time.sleep(0.3)
    try: s.recv(4096)
    except Exception: pass
    s.sendall(b'shutdown\n'); time.sleep(0.5); s.close(); print("telnet-shutdown-sent")
except Exception as e: print("telnet-shutdown-skip:",e)
PYEOF
wait "$OO_PID" 2>/dev/null
echo ">>> restore run done. Verify line below:"
grep -aE "CRC32 =|RESTORE (VERIFIED|MISMATCH)|boot pc" "$GDBLOG" | tail -6
